<?php

/**
 * @file
 * Entity Stages Module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\node\Entity\Node;
use Drupal\user\Entity\User;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;
use Drupal\entity_stages\Manager\ElementManager;
use Drupal\entity_stages\Manager\FormManager;
use Drupal\entity_stages\Manager\ViewManager;

/**
 * Implements entity_stages_preprocess_views_view_table().
 */
function entity_stages_preprocess_views_view_table(&$variables) {
  ViewManager::_preprocessViewsViewTable($variables);
}

/**
 * Implements hook_views_post_execute().
 */
function entity_stages_views_post_execute(ViewExecutable $view) {
  ViewManager::_viewsPostExecute($view);
}

/**
 * Implements hook_views_query_alter().
 */
function entity_stages_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  ViewManager::_viewsQueryAlter($view, $query);
}

/**
 * Implements hook_views_data_alter().
 */
function entity_stages_views_data_alter(array &$data) {
  ViewManager::_viewsDataAlter($data);
}

/**
 * Implements hook_form_alter().
 */
function entity_stages_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  FormManager::_hookFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function entity_stages_menu_local_tasks_alter(&$data, $route_name) {
  ElementManager::_menuLocalTasksAlter($data, $route_name);
}

/**
 * Implements hook_theme_registry_alter().
 */
function entity_stages_theme_registry_alter(&$theme_registry) {
  ElementManager::_themeRegistryAlter($theme_registry);
}

/**
 * Implements hook_entity_base_field_info().
 */
function entity_stages_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'node') {
    // TODO: Use this field as a exposed or not filter to avoid
    // Repeatly ask for approval on same content. Another solution is to pass
    // Revision UID to Administrator if refused, not optimal solutional though.
    $fields['entity_stages_validation_state'] = BaseFieldDefinition::create('string')
      ->setComputed(TRUE);
  }
}

/**
 * Implements hook_node_presave().
 */
function entity_stages_node_presave(Node $node) {
  // Current User.
  $loadCurrentUser = User::load(\Drupal::currentUser()->id());
  $requireValidation =
  !$loadCurrentUser->hasRole('administrator') &&
  !$loadCurrentUser->hasPermission('publish entity stages');

  // If User hasnt permission to publish or modify without validation
  // the content status is either unpublished or
  // published and waiting for validation.
  if ($requireValidation) {
    // If new starts as unpublished.
    if ($node->isNew()) {
      $node->set('status', 0);
    }
    // Else keep current revision.
    else {
      $node->set('status', $node->original->isPublished());
      $node->isDefaultRevision(FALSE);
      $node->original->isDefaultRevision(TRUE);
    }
  }
}
