<?php

/**
 * @file
 * Entity Stages Module.
 */

use Drupal\Core\Site\Settings;
use Drupal\Core\Url;
use Drupal\node\Entity\Node;
use Drupal\user\Entity\User;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info().
 */
function entity_stages_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() == 'node') {
    $fields['entity_stages_validation_state'] = BaseFieldDefinition::create('string')
      ->setComputed(TRUE);
    return $fields;
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function entity_stages_theme_registry_alter(&$theme_registry) {
  // Moderate Content.
  $theme_registry['views_view_table__entity_stages'] = $theme_registry['views_view_table'];
  // $theme_registry['views_view_table__entity_stages']['template'] = 'views-view-table--entity-stages';
  // $theme_registry['views_view_table__entity_stages']['path'] = 'src/Template/views';.
  $theme_registry['views_view_table__entity_stages']['preprocess functions'][] = 'entity_stages_preprocess_views_view_table';
}

/**
 * Implements entity_stages_preprocess_views_view_table().
 */
function entity_stages_preprocess_views_view_table(&$variables) {
  // Register preprocess only if no page Entity Stage.
  $getRoute = \Drupal::request()->get('_route');

  // Get view.
  $view = $variables['view'];

  // Foreach row add uid and role to validate to easy data access.
  if ($view && $view->result && $getRoute == 'view.entity_stages.default_page') {
    foreach ($variables['rows'] as $key => &$row) {
      // Get comparable revisions values.
      $revisionEntity = $view->result[$key]->_entity;
      $nodeLoad = Node::load($revisionEntity->id());

      // Create Operation URLs.
      $urlCompare = Url::fromRoute(
       'diff.revisions_diff',
       [
         'node' => $nodeLoad->id(),
         'left_revision' => $nodeLoad->getRevisionId(),
         'right_revision' => $revisionEntity->getRevisionId(),
         'filter' => 'split_fields',
       ],
       ['absolute' => TRUE]
      )->toString();

      // Open page.
      $pageUrl = Url::fromRoute(
       'entity.node.canonical',
       ['node' => $nodeLoad->id()],
       ['absolute' => TRUE]
      )->toString();

      // Accepter revision/modification.
      $acceptRevision = Url::fromRoute(
      'node.revision_revert_confirm',
      [
        'node' => $nodeLoad->id(),
        'node_revision' => $revisionEntity->getRevisionId(),
      ],
      ['absolute' => TRUE]
      )->toString();

      // Refuser revision/modification.
      $refuserRevision = Url::fromRoute(
      'node.revision_delete_confirm',
      [
        'node' => $nodeLoad->id(),
        'node_revision' => $revisionEntity->getRevisionId(),
      ],
      ['absolute' => TRUE]
      )->toString();

      // Add Node type to Type column.
      $row['columns']['nothing']['content'][0]['field_output']['#markup'] = $nodeLoad->getType();

      // Add route to accept and refuse.
      $row['columns']['dropbutton']['content'][0]['field_output']['#markup'] =
         '<div class="dropbutton-wrapper">
           <div class="dropbutton-widget">
             <ul class="dropbutton">
               <li><a href="' . $urlCompare . '" target="_blank">' . t('Compare') . '</a></li>
               <li><a href="' . $pageUrl . '">' . t('View') . '</a></li>
               <li><a href="' . $acceptRevision . '">' . t('Accept') . '</a></li>
               <li><a href="' . $refuserRevision . '">' . t('Reject') . '</a></li>
             </ul>
           </div>
         </div>';
    }
  }
}

/**
 * Implements hook_views_post_execute().
 */
function entity_stages_views_post_execute(ViewExecutable $view) {
  // Alter only the post query of this view.
  if ($view->storage->get('id') == 'entity_stages') {
    // Filter results before pre render.
    foreach ($view->result as $index => $result) {
      // If some condtions are met ignore the result.
      if (!$result->_entity) {
        unset($view->result[$index]);
        continue;
      }

      // Load entities.
      $nodeLoad = Node::load($result->_entity->nid->value);
      $userLoad = User::load($nodeLoad->uid->target_id);
      $isAdmin = $userLoad->hasRole('administrator');
      $revisionIsOlderThanCurrent = $result->_entity->changed->value < $nodeLoad->changed->value;

      // If some condtions are met ignore the result.
      if ($result->_entity->isDefaultRevision() || $revisionIsOlderThanCurrent || $isAdmin) {
        unset($view->result[$index]);
      }
    }

    // Update rows number and pager.
    // $view->pager->setItemsPerPage(1000);.
    $nbRows = count($view->result);
    $view->total_items = $nbRows;
    $view->pager->total_items = $nbRows;
    $view->pager->updatePageInfo();
    $view->query->view->pager->total_items = $nbRows;
    $view->query->view->pager->updatePageInfo();
  }
}

/**
 * Implements hook_views_query_alter().
 */
function entity_stages_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  $settings = Settings::getAll();
  $currentUser = \Drupal::currentUser();
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function entity_stages_menu_local_tasks_alter(&$data, $route_name) {
  // Add Entity Stages task.
  $data['tabs'][0][] = [
    '#theme' => 'menu_local_task',
    '#active' => $route_name == 'view.entity_stages.default_page',
    '#link' => [
      'title' => t('Entity stages'),
      'url' => Url::fromRoute('view.entity_stages.default_page',
      [],
      ['absolute' => TRUE]),
    ],
  ];
}

/**
 * Implements hook_node_presave().
 */
function entity_stages_node_presave(Node $node) {
  // Current User.
  $loadCurrentUser = User::load(\Drupal::currentUser()->id());
  $requireValidation =
  !$loadCurrentUser->hasRole('administrator') &&
  $loadCurrentUser->hasPermission('requires admin validation');

  // If User hasnt permission to publish or modify without validation
  // the content status is either unpublished or
  // published and waiting for validation.
  if ($requireValidation) {
    // If new starts as unpublished.
    if ($node->isNew()) {
      $node->set('status', 0);
    }
    // Else keep current revision.
    else {
      $node->set('status', $node->original->isPublished());
      $node->isDefaultRevision(FALSE);
      $node->original->isDefaultRevision(TRUE);
    }
  }
}
